M48
; DRILL file {KiCad 6.0.2+dfsg-1} date Wed 25 Jan 2023 11:44:14 AM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-01-25T11:44:14-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.2+dfsg-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.500
%
G90
G05
T1
X201.0Y-59.5
X201.0Y-116.5
X251.0Y-59.5
X251.0Y-116.5
T0
M30
